#! /usr/bin/env php
<?php

use Cpx\Application;

if (isset($GLOBALS['_composer_autoload_path'])) {
    require_once $GLOBALS['_composer_autoload_path'];

    unset($GLOBALS['_composer_autoload_path']);
} else {
    foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
        if (file_exists($file)) {
            require_once $file;

            break;
        }
    }

    unset($file);
}

if (! class_exists(\Symfony\Component\Console\Application::class)) {
    fwrite(STDERR, <<<'MESSAGE'
        cpx is distributed as a standalone PHAR and can no longer be installed through Composer.

        Install the latest release:

          curl -L https://github.com/laravel/cpx/releases/latest/download/cpx -o cpx
          chmod +x cpx
          mv cpx /usr/local/bin/cpx

        MESSAGE . PHP_EOL);

    exit(1);
}

exit((new Application)->run());
